In [36]:
import pandas as pd
import numpy as np
df=pd.read_csv("Employee_Data_100.csv")
df

   Department  Experience  Performance_Score Promoted
0   Marketing        13.8               77.2      Yes
1     Finance        12.9               80.4       No
2          HR         7.3               51.5      Yes
3     Finance         2.3               69.8       No
4     Finance         NaN               78.3       No
..        ...         ...                ...      ...
95         HR         2.3               40.3       No
96    Finance        14.2               74.5       No
97      Sales         6.6               50.7       No
98      Sales         8.2               43.9       No
99         IT         NaN               61.8      Yes

[100 rows x 4 columns]

In [37]:
# How to separate dependent and independent variable:

x=df[['Department','Experience','Performance_Score']]
x

   Department  Experience  Performance_Score
0   Marketing        13.8               77.2
1     Finance        12.9               80.4
2          HR         7.3               51.5
3     Finance         2.3               69.8
4     Finance         NaN               78.3
..        ...         ...                ...
95         HR         2.3               40.3
96    Finance        14.2               74.5
97      Sales         6.6               50.7
98      Sales         8.2               43.9
99         IT         NaN               61.8

[100 rows x 3 columns]

In [38]:
# If we want to create an array for this:

x=df[['Department','Experience','Performance_Score']].values
x

array([['Marketing', 13.8, 77.2],
       ['Finance', 12.9, 80.4],
       ['HR', 7.3, 51.5],
       ['Finance', 2.3, 69.8],
       ['Finance', nan, 78.3],
       ['Sales', 10.4, 52.6],
       ['HR', 10.3, 49.6],
       ['HR', 9.3, 94.0],
       ['HR', 4.8, 68.4],
       ['Finance', 8.9, nan],
       ['Marketing', 6.4, 94.8],
       ['HR', 14.6, 93.1],
       ['Finance', 12.9, 70.7],
       ['Sales', 11.1, 88.5],
       ['Marketing', 4.3, 50.4],
       ['Sales', 4.6, 55.3],
       ['Marketing', 1.6, 78.5],
       ['Finance', 10.9, 86.6],
       ['IT', 2.6, 87.1],
       ['Marketing', 7.2, 62.2],
       ['Sales', 3.8, 88.8],
       ['Finance', 13.5, nan],
       ['Marketing', 7.7, 91.5],
       ['IT', 8.9, 83.2],
       ['IT', 10.7, 76.8],
       ['HR', 3.0, 71.9],
       ['HR', nan, 60.5],
       ['Sales', nan, nan],
       ['Marketing', 3.8, 93.6],
       ['Marketing', 14.2, 55.6],
       ['HR', 9.4, 56.8],
       ['Marketing', 10.7, 66.7],
       ['Marketing', 13.3, nan],
       ['IT', 9.7, 94.7],
       ['HR', 5.1, 49.7],
       ['Finance', nan, 41.0],
       ['HR', nan, 67.2],
       ['Finance', 4.1, 49.8],
       ['IT', 6.8, 60.2],
       ['Sales', 13.4, 80.9],
       ['Marketing', 5.5, 79.7],
       ['IT', 2.7, 56.9],
       ['Marketing', 6.0, 69.8],
       ['Sales', 13.7, 68.0],
       ['Sales', 4.8, 75.0],
       ['IT', 10.1, nan],
       ['Sales', nan, nan],
       ['Finance', 5.9, 93.8],
       ['Sales', 5.3, nan],
       ['Marketing', 3.3, nan],
       ['Marketing', 8.5, 63.9],
       ['Marketing', 7.8, 59.3],
       ['Marketing', 10.7, 75.5],
       ['Finance', 4.8, 76.8],
       ['HR', 4.4, 87.5],
       ['IT', 3.4, 52.7],
       ['Marketing', 4.1, 67.5],
       ['Sales', 8.8, 71.5],
       ['Marketing', 6.7, 82.3],
       ['Sales', 1.9, 42.4],
       ['Sales', 4.6, 94.7],
       ['Marketing', 4.5, 65.8],
       ['Finance', 10.7, 55.4],
       ['Sales', 11.0, 88.6],
       ['Sales', 3.1, 81.1],
       ['Marketing', 15.0, nan],
       ['Sales', 4.7, 58.2],
       ['Sales', 14.7, nan],
       ['Marketing', 6.8, 71.5],
       ['Marketing', 1.5, 93.9],
       ['IT', 5.8, 44.1],
       ['Finance', 9.9, 56.8],
       ['Finance', 10.5, 50.5],
       ['Sales', 8.4, 54.8],
       ['Finance', 7.3, nan],
       ['Sales', 8.7, 60.5],
       ['IT', 9.3, 61.7],
       ['Marketing', 2.1, 86.4],
       ['Marketing', 6.2, 91.2],
       ['Marketing', 4.4, 43.9],
       ['Finance', 12.2, 51.5],
       ['IT', 7.6, 76.9],
       ['Finance', 14.8, 59.7],
       ['Finance', 6.6, 54.0],
       ['IT', 12.4, 56.2],
       ['IT', 12.2, 57.7],
       ['IT', 3.1, 86.7],
       ['IT', nan, 47.5],
       ['Marketing', 10.7, nan],
       ['HR', 13.0, 70.4],
       ['HR', 5.6, 56.3],
       ['IT', 4.1, 63.1],
       ['HR', 11.0, 54.1],
       ['HR', 12.3, 73.6],
       ['IT', nan, 44.5],
       ['HR', 2.3, 40.3],
       ['Finance', 14.2, 74.5],
       ['Sales', 6.6, 50.7],
       ['Sales', 8.2, 43.9],
       ['IT', nan, 61.8]], dtype=object)

In [39]:
y=df[['Promoted']]
y

   Promoted
0       Yes
1        No
2       Yes
3        No
4        No
..      ...
95       No
96       No
97       No
98       No
99      Yes

[100 rows x 1 columns]

In [40]:
y=df['Promoted'].values
y

array(['Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No',
       'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No',
       'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No',
       'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No',
       'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes',
       'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes',
       'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes',
       'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes'],
      dtype=object)

In [41]:
from sklearn.impute import SimpleImputer

In [42]:
imputer= SimpleImputer(missing_values = np.nan,strategy="mean")

In [43]:
x[:,1:3]=imputer.fit_transform(x[:,1:3])
x

array([['Marketing', 13.8, 77.2],
       ['Finance', 12.9, 80.4],
       ['HR', 7.3, 51.5],
       ['Finance', 2.3, 69.8],
       ['Finance', 7.898901098901099, 78.3],
       ['Sales', 10.4, 52.6],
       ['HR', 10.3, 49.6],
       ['HR', 9.3, 94.0],
       ['HR', 4.8, 68.4],
       ['Finance', 8.9, 67.98863636363636],
       ['Marketing', 6.4, 94.8],
       ['HR', 14.6, 93.1],
       ['Finance', 12.9, 70.7],
       ['Sales', 11.1, 88.5],
       ['Marketing', 4.3, 50.4],
       ['Sales', 4.6, 55.3],
       ['Marketing', 1.6, 78.5],
       ['Finance', 10.9, 86.6],
       ['IT', 2.6, 87.1],
       ['Marketing', 7.2, 62.2],
       ['Sales', 3.8, 88.8],
       ['Finance', 13.5, 67.98863636363636],
       ['Marketing', 7.7, 91.5],
       ['IT', 8.9, 83.2],
       ['IT', 10.7, 76.8],
       ['HR', 3.0, 71.9],
       ['HR', 7.898901098901099, 60.5],
       ['Sales', 7.898901098901099, 67.98863636363636],
       ['Marketing', 3.8, 93.6],
       ['Marketing', 14.2, 55.6],
       ['HR', 9.4, 56.8],
       ['Marketing', 10.7, 66.7],
       ['Marketing', 13.3, 67.98863636363636],
       ['IT', 9.7, 94.7],
       ['HR', 5.1, 49.7],
       ['Finance', 7.898901098901099, 41.0],
       ['HR', 7.898901098901099, 67.2],
       ['Finance', 4.1, 49.8],
       ['IT', 6.8, 60.2],
       ['Sales', 13.4, 80.9],
       ['Marketing', 5.5, 79.7],
       ['IT', 2.7, 56.9],
       ['Marketing', 6.0, 69.8],
       ['Sales', 13.7, 68.0],
       ['Sales', 4.8, 75.0],
       ['IT', 10.1, 67.98863636363636],
       ['Sales', 7.898901098901099, 67.98863636363636],
       ['Finance', 5.9, 93.8],
       ['Sales', 5.3, 67.98863636363636],
       ['Marketing', 3.3, 67.98863636363636],
       ['Marketing', 8.5, 63.9],
       ['Marketing', 7.8, 59.3],
       ['Marketing', 10.7, 75.5],
       ['Finance', 4.8, 76.8],
       ['HR', 4.4, 87.5],
       ['IT', 3.4, 52.7],
       ['Marketing', 4.1, 67.5],
       ['Sales', 8.8, 71.5],
       ['Marketing', 6.7, 82.3],
       ['Sales', 1.9, 42.4],
       ['Sales', 4.6, 94.7],
       ['Marketing', 4.5, 65.8],
       ['Finance', 10.7, 55.4],
       ['Sales', 11.0, 88.6],
       ['Sales', 3.1, 81.1],
       ['Marketing', 15.0, 67.98863636363636],
       ['Sales', 4.7, 58.2],
       ['Sales', 14.7, 67.98863636363636],
       ['Marketing', 6.8, 71.5],
       ['Marketing', 1.5, 93.9],
       ['IT', 5.8, 44.1],
       ['Finance', 9.9, 56.8],
       ['Finance', 10.5, 50.5],
       ['Sales', 8.4, 54.8],
       ['Finance', 7.3, 67.98863636363636],
       ['Sales', 8.7, 60.5],
       ['IT', 9.3, 61.7],
       ['Marketing', 2.1, 86.4],
       ['Marketing', 6.2, 91.2],
       ['Marketing', 4.4, 43.9],
       ['Finance', 12.2, 51.5],
       ['IT', 7.6, 76.9],
       ['Finance', 14.8, 59.7],
       ['Finance', 6.6, 54.0],
       ['IT', 12.4, 56.2],
       ['IT', 12.2, 57.7],
       ['IT', 3.1, 86.7],
       ['IT', 7.898901098901099, 47.5],
       ['Marketing', 10.7, 67.98863636363636],
       ['HR', 13.0, 70.4],
       ['HR', 5.6, 56.3],
       ['IT', 4.1, 63.1],
       ['HR', 11.0, 54.1],
       ['HR', 12.3, 73.6],
       ['IT', 7.898901098901099, 44.5],
       ['HR', 2.3, 40.3],
       ['Finance', 14.2, 74.5],
       ['Sales', 6.6, 50.7],
       ['Sales', 8.2, 43.9],
       ['IT', 7.898901098901099, 61.8]], dtype=object)

In [44]:
# Label encoding in machine learning
from sklearn.preprocessing import LabelEncoder

In [45]:
label_encoder_x=LabelEncoder()
x[:,0]=label_encoder_x.fit_transform(x[:,0])
x

array([[3, 13.8, 77.2],
       [0, 12.9, 80.4],
       [1, 7.3, 51.5],
       [0, 2.3, 69.8],
       [0, 7.898901098901099, 78.3],
       [4, 10.4, 52.6],
       [1, 10.3, 49.6],
       [1, 9.3, 94.0],
       [1, 4.8, 68.4],
       [0, 8.9, 67.98863636363636],
       [3, 6.4, 94.8],
       [1, 14.6, 93.1],
       [0, 12.9, 70.7],
       [4, 11.1, 88.5],
       [3, 4.3, 50.4],
       [4, 4.6, 55.3],
       [3, 1.6, 78.5],
       [0, 10.9, 86.6],
       [2, 2.6, 87.1],
       [3, 7.2, 62.2],
       [4, 3.8, 88.8],
       [0, 13.5, 67.98863636363636],
       [3, 7.7, 91.5],
       [2, 8.9, 83.2],
       [2, 10.7, 76.8],
       [1, 3.0, 71.9],
       [1, 7.898901098901099, 60.5],
       [4, 7.898901098901099, 67.98863636363636],
       [3, 3.8, 93.6],
       [3, 14.2, 55.6],
       [1, 9.4, 56.8],
       [3, 10.7, 66.7],
       [3, 13.3, 67.98863636363636],
       [2, 9.7, 94.7],
       [1, 5.1, 49.7],
       [0, 7.898901098901099, 41.0],
       [1, 7.898901098901099, 67.2],
       [0, 4.1, 49.8],
       [2, 6.8, 60.2],
       [4, 13.4, 80.9],
       [3, 5.5, 79.7],
       [2, 2.7, 56.9],
       [3, 6.0, 69.8],
       [4, 13.7, 68.0],
       [4, 4.8, 75.0],
       [2, 10.1, 67.98863636363636],
       [4, 7.898901098901099, 67.98863636363636],
       [0, 5.9, 93.8],
       [4, 5.3, 67.98863636363636],
       [3, 3.3, 67.98863636363636],
       [3, 8.5, 63.9],
       [3, 7.8, 59.3],
       [3, 10.7, 75.5],
       [0, 4.8, 76.8],
       [1, 4.4, 87.5],
       [2, 3.4, 52.7],
       [3, 4.1, 67.5],
       [4, 8.8, 71.5],
       [3, 6.7, 82.3],
       [4, 1.9, 42.4],
       [4, 4.6, 94.7],
       [3, 4.5, 65.8],
       [0, 10.7, 55.4],
       [4, 11.0, 88.6],
       [4, 3.1, 81.1],
       [3, 15.0, 67.98863636363636],
       [4, 4.7, 58.2],
       [4, 14.7, 67.98863636363636],
       [3, 6.8, 71.5],
       [3, 1.5, 93.9],
       [2, 5.8, 44.1],
       [0, 9.9, 56.8],
       [0, 10.5, 50.5],
       [4, 8.4, 54.8],
       [0, 7.3, 67.98863636363636],
       [4, 8.7, 60.5],
       [2, 9.3, 61.7],
       [3, 2.1, 86.4],
       [3, 6.2, 91.2],
       [3, 4.4, 43.9],
       [0, 12.2, 51.5],
       [2, 7.6, 76.9],
       [0, 14.8, 59.7],
       [0, 6.6, 54.0],
       [2, 12.4, 56.2],
       [2, 12.2, 57.7],
       [2, 3.1, 86.7],
       [2, 7.898901098901099, 47.5],
       [3, 10.7, 67.98863636363636],
       [1, 13.0, 70.4],
       [1, 5.6, 56.3],
       [2, 4.1, 63.1],
       [1, 11.0, 54.1],
       [1, 12.3, 73.6],
       [2, 7.898901098901099, 44.5],
       [1, 2.3, 40.3],
       [0, 14.2, 74.5],
       [4, 6.6, 50.7],
       [4, 8.2, 43.9],
       [2, 7.898901098901099, 61.8]], dtype=object)

In [46]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct=ColumnTransformer(
    transformmers=[('encoder',OneHotEncoder(),[0])],
    remainder='passthrough'
)
x=ct.fit_transform(x)

In [47]:
x=onehotencoder.fit_transform(df.Department.values.reshape(-1,1)).toarray()
x

array([[0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.]])

In [48]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [49]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=0
)

In [50]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [31]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

TypeError: Input should have at least 1 dimension i.e. satisfy `len(x.shape) > 0`, got scalar `array(<class 'sklearn.preprocessing._label.LabelEncoder'>, dtype=object)` instead.